provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  google-home-notifier:
    lang: go-wg-armhf
    handler: ./google-home-notifier
    image: kenfdev/home-nextlab:google-home-notifier-0.1.0
    environment:
      write_debug: true
      combine_output: false
      GOOGLE_HOME_HOST: 192.168.100.4
  slack-event-sub:
    lang: go-wg-armhf
    handler: ./slack-event-sub
    image: kenfdev/home-nextlab:slack-event-sub-0.1.0
    environment:
      write_debug: true
      combine_output: false
      GOOGLE_HOME_NOTIFIER_FUNC_URL: http://gateway:8080/function/google-home-notifier
    secrets:
      - bot-user-oauth-access-token
      - slack-verify-token
